config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :quizes, only: %i[index show]
  resources :responses, only: %i[create show index ]
  get '/leaderboards', to: 'responses#leaderboard'
  devise_for :users
  # devise_for :admins
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
$anshash = {}

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :quizze
end

app/models/quizze.rb
class Quizze < ApplicationRecord
  belongs_to :user
  has_many :questions
end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :quizze
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :quizzes,  class_name: "Quizze"
  has_many :responses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @quizes = current_user.quizzes
  end
end

app/controllers/quizes_controller.rb
class QuizesController < ApplicationController
  before_action :authenticate_user!

  def index
        @quizes = current_user.quizze 
  end


  def show
    @quiz = Quizze.find(params[:id])

  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action :authenticate_user!

  def index
    @all_response = current_user.responses
  end
  
  def leaderboard
    @leaderboard = Response.all.order('created_at DESC')
  end

  def show
    @responses = Response.find(params[:id])
  end
  
  def create
    @responses = Response.new
    @responses.user_id = current_user.id
    @responses.quizze_id = params[:quizze_id]
    @responses.score = calculate_score(params)
    
    if @responses.save
      redirect_to  response_path(@responses)
    else
    end   
  end

  private
  def responses_params
    params.require(:response).permit(:user_id,:quizze_id,:score)
  end

  def calculate_score(params)
    count = 0
    hash2 = {}    
    quiz = Quizze.find(params[:quizze_id])
    question = quiz.questions
    question.each do |q| hash2.merge!(q.id=>q.answer)  end

      hash2.stringify_keys!

      hash1 =  params.except(:authenticity_token,:quizze_id,:score,:commit,:controller,:action)

      hash1.each do |key,value| 
        hash2.each do |k,v|
            if key==k && value==v 
                count+=1
            end 
        end 
      end
      return count*5;

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/quizes_helper.rb
module QuizesHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/home/index.html.erb
<% if current_user%>

<%  @quizes.each do |quiz|%>

<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="..." alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title"><%= quiz.score%></h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <%= link_to "Start Quiz",quize_path(:id=>quiz.id),class: "btn btn-primary"%>
  </div>
</div>
<%end%>
<%else%>

<%= render partial: 'shared/hero'%>

<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuizApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render partial: 'shared/navbar'%>
    <%= yield %>
  </body>
</html>

app/views/quizes/show.html.erb
<%= form_for(Response.new, url: responses_path)  do |f| %>
        <div class="modal-content" data-controller="hello">
  <span id='timer' style="font-size:25px;"></span>
  <% @quiz.questions.each do |question| %>
            <div class="modal-header"  data-hello-my-value="<%= current_user.id %>" >
                <h3><%= question.question %></h3>
                <%= hidden_field_tag :quizze_id, @quiz.id %>
            </div>
            <div class="modal-body jkljkl">
                <div class="col-xs-3 5"></div>
                <div class="quiz" id="quiz" data-toggle="buttons">
                     <%=f.label question.op1, class: "element-animation1 btn btn-lg btn-danger btn-block"%>
                    <%= radio_button_tag question.id, question.op1,class: "glyphicon glyphicon-chevron-right" %>
                      <%=f.label question.op2, class: "element-animation1 btn btn-lg btn-danger btn-block"%>
                    <%= radio_button_tag question.id, question.op2,class: "glyphicon glyphicon-chevron-right" %>
                    <%=f.label question.op3, class: "element-animation1 btn btn-lg btn-danger btn-block"%>
                    <%= radio_button_tag question.id, question.op3,class: "glyphicon glyphicon-chevron-right" %>
                    <%=f.label question.op4, class: "element-animation1 btn btn-lg btn-danger btn-block"%>
                    <%= radio_button_tag question.id, question.op4,class: "glyphicon glyphicon-chevron-right" %>
                </div>
            </div>
        </div>
<%end%>
  <%= f.button id: "aryan"%>
<%end%>

  <!-- submit -->

app/views/responses/index.html.erb
<h1>Responses#index</h1>
<p>Find me in app/views/responses/index.html.erb</p>

app/views/responses/leaderboard.html.erb
<h1>All- Responses</h1>


<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">User-Email</th>
      <th scope="col">Quiz-Name</th>
      <th scope="col">Total-Score</th>
      <th scope="col">User-Score</th>
    </tr>
  </thead>
  <tbody>
  <% @leaderboard.each do |response|%>
    <tr>
      <th scope="row"><%= response.id%></th>
      <td><%= response.user.email%></td>
      <td><%= response.quizze.name%></td>
      <td><%= response.quizze.score%></td>
      <td><%= response.score%></td>

    </tr>
    <% end %>
  </tbody>
</table>

app/views/responses/show.html.erb
<h1>Score-Card</h1>

<div class="card">
  <div class="card-header">
    <b><%= @responses.quizze.name%></ b>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p>Total Score=> <%= @responses.quizze.score%></p>
      <b>Your Score=> <%= @responses.score%></b>
      <footer class="blockquote-footer mt-1">Keep Improving U Will Succeed </footer>
    </blockquote>
    <%= link_to "All Responses", responses_path,class: "btn btn-primary"%>
  </div>
</div>

app/views/shared/_hero.html.erb
<div class="bg-dark text-secondary px-4 py-5 text-center">
    <div class="py-5">
      <h1 class="display-5 fw-bold text-white">Welcome To Quiz </h1>
      <div class="col-lg-6 mx-auto">
        <p class="fs-5 mb-4">Quickly design and customize responsive mobile-first sites with Bootstrap, the world’s most popular front-end open source toolkit, featuring Sass variables and mixins, responsive grid system, extensive prebuilt components, and powerful JavaScript plugins.</p>
        <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
          <%=link_to "Sign-up",new_user_registration_path,class:"btn btn-outline-info btn-lg px-4 me-sm-3 fw-bold" %>
          <%=link_to "Login", new_user_session_path,class:"btn btn-outline-light btn-lg px-4"%>
          
        </div>
      </div>
    </div>
  </div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg" style="background-color: 			#3b5998;">
  <div class="container-fluid">
    <a class="navbar-brand text-white" href="/">Quiz</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 nav justify-content-end">
                  <li class="nav-item">
                    <a class="nav-link active text-white" aria-current="page" href="/"><i class="bi bi-house " style = "font-size: 2rem" ></i></a>
                  </li>
                
        <ul>
        <% if user_signed_in?%>
        
         <% if current_user.admin == true%>
        <%=link_to "Admin Dashboard", "/admin" ,class: "nav-link"%>
        <%else %>
        <%= link_to "LeaderBoard",leaderboards_path, class: "nav-link"%>
        <%= link_to "Your Responses",responses_path, class: "nav-link"%>
        <% end %>

        <%end%>
       
        </ul>
        </ul>
        
        <ul>
                  <li class="navbar dropdown ms-auto mb-2 mb-lg-0">
                    <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <% if user_signed_in? %>
                      <%=current_user.email%>
                      <% else %>
                      Toggle
                      <% end %>
                    </a>
                    <ul class="dropdown-menu">
                     <% if user_signed_in? %>
                      <%=button_to "Logout", destroy_user_session_path, method: :delete,class: "dropdown-item"%>
                      <li><%=link_to current_user.email, edit_user_registration_path(:id => current_user.id),class: "dropdown-item"%></li> 
                     <% else %>
                        <%=link_to "Login", new_user_session_path,class: "dropdown-item"%>
                       <%=link_to "Sign-UP", new_user_registration_path,class: "dropdown-item"%>
                     <% end %>
                      
                    </ul>
                  </li>
                  
        </ul>
      
    </div>
  </div>
</nav>